services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aliemre3169
      MYSQL_DATABASE: news_site
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: public-server-1
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
